http:
  port: "8081"
  
american:
  host: "training4-american-api-namani.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "211163834a9c449d9ebf506d4b4cc9fc"
  client_secret: Cb732670BD0B44EC8C2B29Abd5c2674E
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"